In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [5]:
df = pd.read_csv(r'C:\Users\A\Desktop\DepositSense-ML\Dataset\bank.csv')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [6]:
df['deposit']=df['deposit'].map({'yes':1,'no':0})

In [8]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,1
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,1
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,1
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,1
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,1

In [10]:
x=df.drop('deposit',axis=1)
x.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown

In [11]:
y=df['deposit']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: deposit, dtype: int64

In [12]:
num_features=x.select_dtypes(exclude='object').columns
cat_features=x.select_dtypes(include='object').columns

C:\Users\A\AppData\Local\Temp\ipykernel_14688\2845592125.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features=x.select_dtypes(include='object').columns

In [13]:
num_features

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='str')

In [14]:
cat_features

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome'],
      dtype='str')

In [15]:
numareic_transformer=StandardScaler()
cat_transformer=OneHotEncoder()

In [16]:
preprocesser=ColumnTransformer(
    [
        ("standardscaler",numareic_transformer,num_features),
        ('onehotencoder',cat_transformer,cat_features)
    ]
)

In [17]:
x=preprocesser.fit_transform(x)

In [18]:
x.shape

(11162, 51)

In [19]:
x

array([[ 1.49150488,  0.25252514, -1.26574556, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.23967567, -0.4599736 , -1.26574556, ...,  0.        ,
         0.        ,  1.        ],
       [-0.0194704 , -0.0801603 , -1.26574556, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-0.77495804, -0.46493443,  0.39689074, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.14841574, -0.47392593, -0.90946635, ...,  0.        ,
         0.        ,  0.        ],
       [-0.6070719 , -0.47392593, -0.79070662, ...,  0.        ,
         0.        ,  1.        ]], shape=(11162, 51))

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [21]:
x_train.shape,x_test.shape

((7813, 51), (3349, 51))

In [22]:
models={
    'Logistic_regression':LogisticRegression(),
    'svm':SVC(),
    'Navi_bayas':GaussianNB(),
    'Random_forest':RandomForestClassifier(),
    'Decision_tree':DecisionTreeClassifier(),
    'Knn':KNeighborsClassifier()
   }

In [26]:
model_list=[]
for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(x_train,y_train)
  y_predict=model.predict(x_test)
  print(list(models.keys())[i])
  print(f'Accuracy:-{accuracy_score(y_predict,y_test)}')
  print(confusion_matrix(y_predict,y_test))
  print(classification_report(y_predict,y_test))
  print('='*35)
  print('\n')

Logistic_regression
Accuracy:-0.8205434458047178
[[1479  338]
 [ 263 1269]]
              precision    recall  f1-score   support

           0       0.85      0.81      0.83      1817
           1       0.79      0.83      0.81      1532

    accuracy                           0.82      3349
   macro avg       0.82      0.82      0.82      3349
weighted avg       0.82      0.82      0.82      3349

===================================


svm
Accuracy:-0.8489101224246044
[[1444  208]
 [ 298 1399]]
              precision    recall  f1-score   support

           0       0.83      0.87      0.85      1652
           1       0.87      0.82      0.85      1697

    accuracy                           0.85      3349
   macro avg       0.85      0.85      0.85      3349
weighted avg       0.85      0.85      0.85      3349

===================================


Navi_bayas
Accuracy:-0.7229023589131084
[[1497  683]
 [ 245  924]]
              precision    recall  f1-score   support

           0       0.86      0.69      0.76      2180
           1       0.57      0.79      0.67      1169

    accuracy                           0.72      3349
   macro avg       0.72      0.74      0.71      3349
weighted avg       0.76      0.72      0.73      3349

===================================


Random_forest
Accuracy:-0.8453269632726187
[[1427  203]
 [ 315 1404]]
              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1630
           1       0.87      0.82      0.84      1719

    accuracy                           0.85      3349
   macro avg       0.85      0.85      0.85      3349
weighted avg       0.85      0.85      0.85      3349

===================================


Decision_tree
Accuracy:-0.7859062406688564
[[1393  368]
 [ 349 1239]]
              precision    recall  f1-score   support

           0       0.80      0.79      0.80      1761
           1       0.77      0.78      0.78      1588

    accuracy                           0.79      3349
   macro avg       0.79      0.79      0.79      3349
weighted avg       0.79      0.79      0.79      3349

===================================


Knn
Accuracy:-0.8029262466407883
[[1479  397]
 [ 263 1210]]
              precision    recall  f1-score   support

           0       0.85      0.79      0.82      1876
           1       0.75      0.82      0.79      1473

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.81      0.80      0.80      3349

===================================